export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  REPORT_NOT_FOUND: "REPORT_NOT_FOUND",
  REPORT_ALREADY_PROCESSED: "REPORT_ALREADY_PROCESSED",
  REPORT_ACTION_INVALID: "REPORT_ACTION_INVALID",
  FACILITY_NOT_FOUND: "FACILITY_NOT_FOUND",
  FACILITY_STATUS_INVALID: "FACILITY_STATUS_INVALID"
} as const;
